# Managed by Ansible. Active color: green

upstream catalog_backend {
    server green-catalog:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream cart_backend {
    server green-cart:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream checkout_backend {
    server green-checkout:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream payment_backend {
    server green-payment:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream user_backend {
    server green-user:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

