# Managed by Ansible. Active color: blue

upstream catalog_backend {
    server blue-catalog:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream cart_backend {
    server blue-cart:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream checkout_backend {
    server blue-checkout:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream payment_backend {
    server blue-payment:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

upstream user_backend {
    server blue-user:8080 max_fails=1 fail_timeout=1s;
    keepalive 32;
}

